Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: true

Metrics/ClassLength:
  Enabled: false
  Max: 150

Metrics/MethodLength:
  Enabled: true
  Max: 99

Metrics/AbcSize:
  Enabled: true
  Max: 150

Layout/LineLength:
  Enabled: true
  Max: 99
  AllowHeredoc: false

Layout/TrailingWhitespace:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: true
  MinNameLength: 2

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/SpaceAfterMethodName:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/NegatedUnless:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/For:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/OrAssignment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Not:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
